version: "3.8"
   
services:
  web:
    build: .
    command: sh -c "python manage.py makemigrations --noinput && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
